/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-library-conventions")
    id("com.diffplug.spotless")
    id("io.gitlab.arturbosch.detekt") version "1.23.7"
}

spotless {
    kotlin {
        target("**/*.kt")
        ktfmt()
    }
}

detekt {
    toolVersion = "1.23.7"
}
