/*
 * This file was generated by the Gradle 'init' task.
 */

plugins { id("buildlogic.kotlin-library-conventions") }

dependencies {
  implementation("org.apache.commons:commons-text")
  implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.18.3")
  testImplementation(kotlin("test"))
}
