/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
  id("buildlogic.kotlin-library-conventions")
  id("com.diffplug.spotless")
  id("io.gitlab.arturbosch.detekt") version "1.23.7"
}

spotless {
  kotlin {
    target("**/*.kt")
    ktfmt()
  }
}

detekt {
  toolVersion = "1.23.7"
  buildUponDefaultConfig = true
  config.setFrom(files("${rootProject.projectDir}/config/detekt/detekt.yml"))
}

dependencies {
  implementation("org.apache.commons:commons-text")
  implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.18.3")
  testImplementation(kotlin("test"))
}


