/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app

import org.apache.commons.text.WordUtils
import org.example.utilities.StringUtils

fun main() {
  val tokens = StringUtils.split(MessageUtils.MESSAGE)
  val result = StringUtils.join(tokens)
  println(WordUtils.capitalize(result))
}
