/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
  id("buildlogic.kotlin-application-conventions")
  id("com.diffplug.spotless")
  id("io.gitlab.arturbosch.detekt") version "1.23.7"
}

spotless {
  kotlin {
    target("**/*.kt")
    ktfmt()
  }
}

detekt { toolVersion = "1.23.7" }

dependencies {
  implementation("org.apache.commons:commons-text")
  testImplementation(kotlin("test"))
}

application {
  // Define the main class for the application.
  mainClass = "ru.kislball.machikoro.App"
}
