style:
  ForbiddenComment:
    active: false
  MagicNumber:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
  ReturnCount:
    active: false

complexity:
  LongMethod:
    active: false
  LongParameterList:
    functionThreshold: 7
    constructorThreshold: 16
  TooManyFunctions:
    active: false

naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  MatchingDeclarationName:
    active: false

performance:
  SpreadOperator:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
  ThrowingExceptionsWithoutMessageOrCause:
    active: false
