style:
  ForbiddenComment:
    active: false
  MagicNumber:
    active: false

complexity:
  LongParameterList:
    constructorThreshold: 16

performance:
  SpreadOperator:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
