style:
  ForbiddenComment:
    active: false
  MagicNumber:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
  ReturnCount:
    active: false

complexity:
  LongMethod:
    active: false
  LongParameterList:
    constructorThreshold: 16
  TooManyFunctions:
    active: false

performance:
  SpreadOperator:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
  ThrowingExceptionsWithoutMessageOrCause:
    active: false
